"""
Graviton Live Dashboard Generator and Auto-Updater package.

Re-exports public and internal API for full backwards compatibility.
"""

from lib.dashboard.common import (
    REPO_ROOT,
    _DETECTED_REPO,
    _DETECTED_REPO_CHECKED,
    _build_pacing_details,
    _detect_git_repo_full_name,
    _extract_countdown,
    _reset_detected_repo_cache,
    calculate_target_pacing_from_details,
    format_duration,
    format_percentage,
    get_quota_color,
    is_safe_url,
    logger,
    parse_countdown_to_seconds,
    resolve_target_url,
)
from lib.dashboard.html import (
    _DASHBOARD_TEMPLATE_CACHE,
    _TEMPLATE_LOCK,
    _enrich_dashboard_data,
    _format_reload_state_class,
    _format_target_html_cell,
    _get_dashboard_template,
    _get_fallback_dashboard_template,
    _pacing_style_and_title,
    _render_active_tasks_table,
    _render_approved_prs_table,
    _render_header_html,
    _render_history_tasks_table,
    _render_metrics_html,
    _render_queued_tasks_table,
    _render_quota_card,
    _render_quota_html,
    _reset_dashboard_template_cache,
    _safe_disp,
    get_cached_git_info,
    get_hot_reload_state,
    render_dashboard_html,
)
from lib.dashboard.markdown import (
    _fmt_window_val_and_details,
    _format_target_markdown_cell,
    _gather_markdown_context,
    _md_active_tasks,
    _md_approved_prs,
    _md_footer,
    _md_header,
    _md_history,
    _md_pipeline,
    _md_quota,
    _md_quota_gemini_rows,
    _md_quota_third_party_rows,
    _md_queued,
    format_dashboard_markdown,
)
from lib.dashboard.parser import (
    MD_LINK_PATTERN,
    METRIC_INT_PATTERNS,
    METRIC_STR_PATTERNS,
    SECTION_SPLIT_PATTERN,
    SERVER_PATTERN,
    STATUS_CLEANUP_PATTERN,
    STATUS_HISTORY_CLEANUP_PATTERN,
    STATUS_PATTERN,
    UPDATED_PATTERN,
    WORKERS_PATTERN,
    _extract_table_rows,
    _parse_active,
    _parse_header,
    _parse_history,
    _parse_metrics,
    _parse_pct,
    _parse_prs,
    _parse_quota,
    _parse_queued,
    _parse_target_cell,
    parse_dashboard_markdown,
)
from lib.dashboard.updater import DashboardUpdater

__all__ = [
    # common
    "REPO_ROOT",
    "logger",
    "format_duration",
    "format_percentage",
    "is_safe_url",
    "get_quota_color",
    "parse_countdown_to_seconds",
    "_extract_countdown",
    "calculate_target_pacing_from_details",
    "_build_pacing_details",
    "resolve_target_url",
    "_detect_git_repo_full_name",
    "_reset_detected_repo_cache",
    # markdown
    "format_dashboard_markdown",
    "_format_target_markdown_cell",
    "_fmt_window_val_and_details",
    "_gather_markdown_context",
    "_md_header",
    "_md_pipeline",
    "_md_active_tasks",
    "_md_quota",
    "_md_quota_gemini_rows",
    "_md_quota_third_party_rows",
    "_md_queued",
    "_md_approved_prs",
    "_md_history",
    "_md_footer",
    # parser
    "parse_dashboard_markdown",
    "_parse_target_cell",
    "_extract_table_rows",
    "_parse_pct",
    "_parse_header",
    "_parse_metrics",
    "_parse_quota",
    "_parse_active",
    "_parse_queued",
    "_parse_prs",
    "_parse_history",
    "SERVER_PATTERN",
    "STATUS_PATTERN",
    "UPDATED_PATTERN",
    "WORKERS_PATTERN",
    "METRIC_INT_PATTERNS",
    "METRIC_STR_PATTERNS",
    "SECTION_SPLIT_PATTERN",
    "STATUS_CLEANUP_PATTERN",
    "STATUS_HISTORY_CLEANUP_PATTERN",
    "MD_LINK_PATTERN",
    # html
    "render_dashboard_html",
    "_render_active_tasks_table",
    "_render_queued_tasks_table",
    "_render_approved_prs_table",
    "_render_history_tasks_table",
    "_get_dashboard_template",
    "_reset_dashboard_template_cache",
    "_get_fallback_dashboard_template",
    "_format_reload_state_class",
    "_format_target_html_cell",
    "_pacing_style_and_title",
    "_safe_disp",
    "_enrich_dashboard_data",
    "_render_header_html",
    "_render_metrics_html",
    "_render_quota_card",
    "_render_quota_html",
    "_TEMPLATE_LOCK",
    "_DASHBOARD_TEMPLATE_CACHE",
    "get_cached_git_info",
    "get_hot_reload_state",
    # updater
    "DashboardUpdater",
]
